type TradingCard = {
  name: string;
  rarity: string;
  description: string;
};

// //_______________TEST ARRAY_________________
// export const tradingCards: TradingCard[] = [
//   { name: "item 0", rarity: "0", description: "itemDes 0" },
//   { name: "item 1", rarity: "1", description: "itemDes 1" },
//   { name: "item 2", rarity: "2", description: "itemDes 2" },
//   { name: "item 3", rarity: "3", description: "itemDes 3" },
//   { name: "item 4", rarity: "4", description: "itemDes 4" },
//   { name: "item 5", rarity: "5", description: "itemDes 5" },
//   { name: "item 6", rarity: "6", description: "itemDes 6" },
//   { name: "item 7", rarity: "7", description: "itemDes 7" },
//   { name: "item 8", rarity: "8", description: "itemDes 8" },
//   { name: "item 9", rarity: "9", description: "itemDes 9" },
//   { name: "item 10", rarity: "10", description: "itemDes 10" },
//   { name: "item 11", rarity: "11", description: "itemDes 11" },
//   { name: "item 12", rarity: "12", description: "itemDes 12" },
//   { name: "item 13", rarity: "13", description: "itemDes 13" },
//   { name: "item 14", rarity: "14", description: "itemDes 14" },
//   { name: "item 15", rarity: "15", description: "itemDes 15" },
//   { name: "item 16", rarity: "16", description: "itemDes 16" },
//   { name: "item 17", rarity: "17", description: "itemDes 17" },
//   { name: "item 18", rarity: "18", description: "itemDes 18" },
//   { name: "item 19", rarity: "19", description: "itemDes 19" },
//   { name: "item 20", rarity: "20", description: "itemDes 20" },
//   { name: "item 21", rarity: "21", description: "itemDes 21" },
//   { name: "item 22", rarity: "22", description: "itemDes 22" },
//   { name: "item 23", rarity: "23", description: "itemDes 23" },
//   { name: "item 24", rarity: "24", description: "itemDes 24" },
//   { name: "item 25", rarity: "25", description: "itemDes 25" },
//   { name: "item 26", rarity: "26", description: "itemDes 26" },
//   { name: "item 27", rarity: "27", description: "itemDes 27" },
//   { name: "item 28", rarity: "28", description: "itemDes 28" },
//   { name: "item 29", rarity: "29", description: "itemDes 29" },
// ];

export const replacedCards: TradingCard[] = [];

export const tradingCards: TradingCard[] = [
  { name: "Dads Lost Coin", rarity: "Common", description: "When anyone rolls a 1, you may reroll it." },
  { name: "Dinner", rarity: "Rare", description: "+1 HP" },
  { name: "Pay to Play", rarity: "Legendary", description: "Pay 10: Steal an item from any player." },
  { name: "Belly Button", rarity: "Rare", description: "You may play an additional loot card on your turn. Each time you take damage, you may recharge your character." },
  { name: "Bob's Brain", rarity: "Legendary", description: "Each time you declare an attack, Roll; (1-2: Deal 1 damage to a monster. 3-4: Deal 1 damage to a player. 5-6: Take 1 damage.)" },
  { name: "Brimstone", rarity: "Rare", description: "+1 Dmg. Each time you deal combat damage to a monster, deal 1 damage to another player." },
  { name: "Mom's Purse", rarity: "Common", description: "Loot +1 during your loot step." },
  { name: "The Chest", rarity: "Legendary", description: "If this would be destroyed it becomes a soul instead." },
  //Fake Cards
  { name: "The Ladder", rarity: "Common", description: "You may attack any monster in the dungeon without a line of sight." },
  { name: "Guppy's Collar", rarity: "Rare", description: "When you die, roll; (1: Revive with 1 health. 2-6: Stay dead.)" },
  { name: "Guppy's Hairball", rarity: "Common", description: "Add +1 to your attack roll." },
  { name: "Guppy's Head", rarity: "Rare", description: "Deal 1 damage to any target. If this kills a monster, gain +1 loot card." },
  { name: "Guppy's Tail", rarity: "Common", description: "Loot +1 during your loot step." },
  { name: "Habit", rarity: "Rare", description: "When you take damage, you may recharge your character." },
  { name: "Holy Grail", rarity: "Common", description: "+1 HP." },
  { name: "Humbleing Bundle", rarity: "Legendary", description: "Double the rewards when a monster or loot card is destroyed." },
  { name: "The Jar", rarity: "Common", description: "Store up to 2 additional loot cards. Destroy this card after use." },
  { name: "Joker", rarity: "Rare", description: "Draw 2 loot cards and gain a soul." },
  { name: "The Left Hand", rarity: "Common", description: "When you roll during a loot card or monster draw, you may change a heart result to a soul result." },
  { name: "Lil Brimstone", rarity: "Rare", description: "+1 Dmg. Deal 1 damage to any target." },
  { name: "Lil Chubby", rarity: "Common", description: "You may attack any target in the dungeon." },
  { name: "Lil Gurdy", rarity: "Common", description: "You may attack any target in the dungeon." },
  { name: "Little Baggy", rarity: "Rare", description: "Draw 1 additional loot card during your loot step." },
  { name: "Lump of Coal", rarity: "Rare", description: "+1 Dmg. Add +1 to your attack roll." },
  { name: "Lusty Blood", rarity: "Legendary", description: "Each time you kill a monster, gain +1 damage until the end of your turn." },
  { name: "Magic Mushroom", rarity: "Rare", description: "+1 Dmg. +1 HP." },
  { name: "Magneto", rarity: "Common", description: "Draw an additional loot card during your loot step." },
  { name: "The Mark", rarity: "Rare", description: "+1 Dmg." },
  { name: "Maw of the Void", rarity: "Legendary", description: "Destroy any monster." },
  { name: "Meat!", rarity: "Common", description: "+1 HP." },
  { name: "Mom's Box", rarity: "Rare", description: "Recharge any item card in play." },
  { name: "Mom's Coin Purse", rarity: "Common", description: "Draw 2 loot cards." },
  { name: "Mom's Eye", rarity: "Common", description: "You may attack any target in the dungeon." },
  { name: "Mom's Heels", rarity: "Common", description: "You may attack any target in the dungeon." },
  { name: "Mom's Key", rarity: "Rare", description: "Loot +1 during your loot step." },
  { name: "Mom's Knife", rarity: "Legendary", description: "Deal 2 damage to any target." },
  { name: "Mom's Pad", rarity: "Common", description: "You may attack any target in the dungeon." },
  { name: "Mom's Pearls", rarity: "Common", description: "+1 HP." },
  { name: "Mom's Razor", rarity: "Rare", description: "Each time you deal combat damage to a monster, deal 1 damage to another player." },
  { name: "Mom's Shovel", rarity: "Common", description: "You may attack any target in the dungeon." },
  { name: "Mom's Underwear", rarity: "Common", description: "You may attack any target in the dungeon." },
  { name: "Monster Manual", rarity: "Rare", description: "Draw 1 loot card." },
  { name: "My Reflection", rarity: "Common", description: "Roll a die. On a 1, deal 1 damage to any target." },
  { name: "Mysterious Liquid", rarity: "Rare", description: "+1 Dmg. Deal 1 damage to any target." },
  { name: "Notched Axe", rarity: "Common", description: "Destroy any obstacle." },
  { name: "Number One", rarity: "Common", description: "Draw 2 additional loot cards during your loot step." },
  { name: "Odd Mushroom (Thin)", rarity: "Common", description: "+1 Dmg." },
  { name: "Odd Mushroom (Thick)", rarity: "Common", description: "+1 HP." },
  { name: "The Pact", rarity: "Rare", description: "+1 Dmg. +1 HP." },
  { name: "Pandora's Box", rarity: "Legendary", description: "Destroy any monster." },
  { name: "Pentagram", rarity: "Rare", description: "+1 Dmg." },
  { name: "PhD", rarity: "Rare", description: "Draw 1 additional loot card during your loot step." },
  { name: "Polydactyly", rarity: "Common", description: "Draw 2 additional loot cards during your loot step." },
  { name: "Pony", rarity: "Common", description: "You may attack any target in the dungeon." },
  { name: "Punching Bag", rarity: "Common", description: "You may attack any target in the dungeon." },
  { name: "Pyro", rarity: "Legendary", description: "+1 Dmg. Deal 1 damage to any target." },
  { name: "The Quarter", rarity: "Rare", description: "Draw 2 additional loot cards during your loot step." },
  { name: "Rainbow Baby", rarity: "Common", description: "You may attack any target in the dungeon." },
  { name: "The Relic", rarity: "Rare", description: "Gain +1 soul at the start of your turn." },
  { name: "Roid Rage", rarity: "Common", description: "+1 Dmg." },
  { name: "The Rosary", rarity: "Common", description: "Gain +1 soul at the start of your turn." },
  { name: "Rotten Baby", rarity: "Common", description: "You may attack any target in the dungeon." },
  { name: "The Sad Onion", rarity: "Common", description: "+1 Dmg." },
  { name: "Sack of Pennies", rarity: "Common", description: "Draw 1 loot card." },
  { name: "Sack Head", rarity: "Rare", description: "Draw 2 additional loot cards during your loot step." },
  { name: "Sacrificial Altar", rarity: "Legendary", description: "Destroy a non-eternal monster and gain 1 soul." },
  { name: "Sacred Heart", rarity: "Legendary", description: "+1 Dmg. +1 HP." },
  { name: "The Satanic Bible", rarity: "Rare", description: "Recharge any item card in play." },
  { name: "Scapegoat", rarity: "Common", description: "You may attack any target in the dungeon." },
  { name: "Scapular", rarity: "Common", description: "Gain +1 soul at the start of your turn." },
  { name: "The Screw", rarity: "Common", description: "+1 Dmg." },
  { name: "Sharp Plug", rarity: "Rare", description: "Recharge any item card in play." },
  { name: "Sister Maggy", rarity: "Common", description: "You may attack any target in the dungeon." },
  { name: "Skatole", rarity: "Common", description: "You may attack any target in the dungeon." },
  { name: "Skeleton Key", rarity: "Rare", description: "Draw 2 additional loot cards during your loot step." },
  { name: "Smart Fly", rarity: "Common", description: "You may attack any target in the dungeon." },
  { name: "SMB Super Fan", rarity: "Common", description: "+1 Dmg. +1 HP." },
  { name: "Soy Milk", rarity: "Common", description: "Draw 2 additional loot cards during your loot step." },
  { name: "Speed Ball", rarity: "Common", description: "+1 Dmg." },
  { name: "Spider Mod", rarity: "Common", description: "Draw 1 loot card." },
  { name: "Spoon Bender", rarity: "Rare", description: "Deal 1 damage to any target." },
  { name: "Steam Sale", rarity: "Rare", description: "Draw 2 additional loot cards during your loot step." },
  { name: "Steven", rarity: "Common", description: "+1 Dmg." },
  { name: "Stigmata", rarity: "Common", description: "+1 Dmg. +1 HP." },
  { name: "Stop Watch", rarity: "Legendary", description: "Draw 1 additional loot card during your loot step." },
  { name: "Strange Attractor", rarity: "Rare", description: "Draw 1 loot card." },
  { name: "The Sun", rarity: "Rare", description: "Draw 2 additional loot cards during your loot step." },
  { name: "Synthoil", rarity: "Common", description: "+1 Dmg." },
  { name: "Tammy's Head", rarity: "Rare", description: "Deal 1 damage to any target." },
  { name: "Technology", rarity: "Common", description: "Deal 1 damage to any target." },
  { name: "Technology 2", rarity: "Rare", description: "Deal 1 damage to any target." },
  { name: "Teleport", rarity: "Common", description: "Teleport to any room on the board." },
  { name: "The Halo", rarity: "Rare", description: "+1 Dmg. +1 HP." },
  { name: "The Inner Eye", rarity: "Rare", description: "Deal 1 damage to any target." },
  { name: "The Ludovico Technique", rarity: "Legendary", description: "Deal 2 damage to any target." },
  { name: "The Mind", rarity: "Legendary", description: "See the top 3 cards of the monster deck. You may put them back in any order." },
  { name: "The Mulligan", rarity: "Rare", description: "Deal 1 damage to any target." },
  { name: "The Parasite", rarity: "Common", description: "Deal 1 damage to any target." },
  { name: "The Wafer", rarity: "Rare", description: "+1 Dmg. +1 HP." },
  { name: "Three Dollar Bill", rarity: "Common", description: "Deal 1 damage to any target." },
  { name: "Thunder Thighs", rarity: "Common", description: "Destroy any obstacle." },
  { name: "Tiny Planet", rarity: "Rare", description: "Deal 1 damage to any target." },
  { name: "Torn Photo", rarity: "Common", description: "+1 Dmg." },
  { name: "Transcendence", rarity: "Common", description: "You may attack any target in the dungeon." },
  { name: "Treasure Map", rarity: "Rare", description: "Look at the top 3 cards of the monster deck. You may put them back in any order." },
  { name: "Trinity Shield", rarity: "Legendary", description: "Prevent up to 2 damage during your turn." },
  { name: "The Virus", rarity: "Common", description: "Deal 1 damage to any target." },
  { name: "Virgo", rarity: "Rare", description: "Draw 1 additional loot card during your loot step." },
  { name: "The Wiz", rarity: "Common", description: "Deal 1 damage to any target." },
  { name: "Yum Heart", rarity: "Common", description: "Heal 2 HP." },
];
